src/html5Templates.Web/Models/KitchenSink.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace html5Templates.Web.Models
{
    public class KitchenSink
    {
        /* Note: [DataType("TemplateName")] and Mvc's [UIHint("TemplateName")] are equivalent for our purposes */

        public string RegularString { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [DataType(DataType.Url)]
        public string Url { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [DataType("Search")]
        public string Search { get; set; }

        //[DataType(DataType.DateTime)] //Redundant
        public DateTime DateTime { get; set; }
        
        [DataType("DateTime-Local")]
        public DateTime DateTimeLocal { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateOnly { get; set; }

        [DataType(DataType.Time)]
        public string TimeOnly { get; set; }

        [DataType("Month")]
        public string Month { get; set; }

        [DataType("Week")]
        public string Week { get; set; }

        [DataType("Number")] //On Opera number uses a spinbox, so this will only work with integers
        public int Number { get; set; }

        [DataType("Color")]
        public string Color { get; set; }
    }
}

src/html5Templates.Web/Controllers/DemoController.cs
using System.Web.Mvc;
using html5Templates.Web.Models;

namespace html5Templates.Web.Controllers
{
    public class DemoController : Controller
    {
        //
        // GET: /Demo/

        public ActionResult Index()
        {
            return RedirectToAction("KitchenSink");
        }

        public ActionResult KitchenSink()
        {
            var kitchenSink = new KitchenSink();

            return View(kitchenSink);
        }
    }
}

src/html5Templates.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace html5Templates.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/html5Templates.Web/Views/Demo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

src/html5Templates.Web/Views/Demo/KitchenSink.cshtml
@model html5Templates.Web.Models.KitchenSink

@{
    ViewBag.Title = "KitchenSink";
}

<h2>KitchenSink</h2>

<h3>This demo has all of the implemented HTML5 input types in one place</h3>
<p>
    <a href="#source" >Look below</a> to see the underlying source code which proves it's written with buttery HTML5 goodness
</p>

@using (Html.BeginForm("KitchenSink", "Demo", FormMethod.Get)) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>All Input Types</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RegularString)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegularString)
            @Html.ValidationMessageFor(model => model.RegularString)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Url)
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Search)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Search)
            @Html.ValidationMessageFor(model => model.Search)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTime)
            @Html.ValidationMessageFor(model => model.DateTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateTimeLocal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTimeLocal)
            @Html.ValidationMessageFor(model => model.DateTimeLocal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOnly)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOnly)
            @Html.ValidationMessageFor(model => model.DateOnly)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TimeOnly)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TimeOnly)
            @Html.ValidationMessageFor(model => model.TimeOnly)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Month)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Month)
            @Html.ValidationMessageFor(model => model.Month)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Week)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Week)
            @Html.ValidationMessageFor(model => model.Week)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Color)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Color)
            @Html.ValidationMessageFor(model => model.Color)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<h2>Source code for this page</h2>
<div id="source">
<pre class="prettyprint">
public class Something {
    //Code comment
}
</pre>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
    $(function () {
        var html = htmlEncode($('form').html());
        $('#source > pre.prettyprint').html(html);

        prettyPrint();
    });

    function htmlEncode(value) {
        return $('<div/>').text(value).html();
    }

</script>

src/html5Templates.Web/Views/Demo/ViewPage1.cshtml
@model html5Templates.Web.Models.KitchenSink

@{
    ViewBag.Title = "ViewPage1";
}

<h2>ViewPage1</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>KitchenSink</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RegularString)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RegularString)
            @Html.ValidationMessageFor(model => model.RegularString)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Url)
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Search)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Search)
            @Html.ValidationMessageFor(model => model.Search)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTime)
            @Html.ValidationMessageFor(model => model.DateTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateTimeLocal)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateTimeLocal)
            @Html.ValidationMessageFor(model => model.DateTimeLocal)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateOnly)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateOnly)
            @Html.ValidationMessageFor(model => model.DateOnly)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TimeOnly)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TimeOnly)
            @Html.ValidationMessageFor(model => model.TimeOnly)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Month)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Month)
            @Html.ValidationMessageFor(model => model.Month)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Week)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Week)
            @Html.ValidationMessageFor(model => model.Week)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Number)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Color)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Color)
            @Html.ValidationMessageFor(model => model.Color)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/html5Templates.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome to the Html5 Mvc Templates Project!</h2>

<h3>Samples</h3>
<ul>
    <li>@Html.ActionLink("All Demos", "KitchenSink", "Demo")</li>
</ul>

src/html5Templates.Web/Views/Shared/EditorTemplates/Color.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "color" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Date.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "date" })

src/html5Templates.Web/Views/Shared/EditorTemplates/DateTime-Local.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "datetime-local" })

src/html5Templates.Web/Views/Shared/EditorTemplates/DateTime.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "datetime" })

src/html5Templates.Web/Views/Shared/EditorTemplates/EmailAddress.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "email" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Month.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "month" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Number.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "number" })

src/html5Templates.Web/Views/Shared/EditorTemplates/PhoneNumber.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "tel" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Search.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "search" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Time.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "time" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Url.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "url" })

src/html5Templates.Web/Views/Shared/EditorTemplates/Week.cshtml
@Html.TextBox("", ViewData.TemplateInfo.FormattedModelValue, new { @class = "text-box single-line", type = "week" })

src/html5Templates.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Css/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Css/prettify.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/prettify.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>